/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.IOException;
import java.lang.reflect.Constructor;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;


public class App {
    private static Logger logger = LogManager.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Throwable {
        String problem = args[0];
        boolean example = args.length == 2;
        Class<?> solutionClass = Class.forName("aoc.Day" + problem);
        Constructor<?> solutionConstructor = solutionClass.getConstructor();
        Solution solution = (Solution) solutionConstructor.newInstance();

        long start = System.currentTimeMillis();
        solution.loadInput(example);
        logger.info("Load input: \t\ttook {} seconds", (System.currentTimeMillis() - start) * 0.001);

        start = System.currentTimeMillis();
        String solution1 = solution.solution1();
        logger.info("Solution 1: {}\t took {} seconds", solution1, (System.currentTimeMillis() - start) * 0.001);

        start = System.currentTimeMillis();
        String solution2 = solution.solution2();
        logger.info("Solution 2: {}\t took {} seconds", solution2, (System.currentTimeMillis() - start) * 0.001);
    }
}
